{% set name = "apache-beam" %}
{% set version = "2.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: bba920cc787dfdc193f2d65b8a8cb8e1e1a8766d8170f5cdfcf5ed0dfe65dcdd

build:
  number: 1
  skip: True  # [win]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
  run:
    - python
    - cython >=0.23
    - python-avro >=1.8.1,<2.0.0
    - crcmod >=1.7,<2.0
    - dill >=0.2.9,<0.2.10
    - fastavro >=0.21.4,<0.22
    - pyarrow >=0.12.0,<0.15.0
    - grpcio >=1.8,<2
    - python-hdfs >=2.1.0,<3.0.0
    - httplib2 >=0.8,<=0.12.0
    - mock >=1.0.1,<3.0.0
    - oauth2client >=2.0.1,<5
    - protobuf >=3.5.0.post1,<4
    - pydot >=1.2.0,<2
    - pymongo >=3.8.0,<4.0.0
    - pytz >=2018.3
    - pyyaml >=3.12,<4.0.0
    - python-dateutil >=2.8.0,<3
    - pyvcf >=0.6.8,<0.7.0  # [py<3]
    - six >=1.9,<1.12
    - typing >=3.6.0,<3.7.0  # [py<35]
    - futures >=3.2.0,<4.0.0  # [py<3]
    - future >=0.16.0,<1.0.0
 

test:
  imports:
    - apache_beam
    - apache_beam.coders
    - apache_beam.examples.complete.game
    - apache_beam.examples.complete.juliaset
    - apache_beam.examples.complete.juliaset.juliaset
    - apache_beam.examples.cookbook
    - apache_beam.examples.flink    
    - apache_beam.examples.snippets
    - apache_beam.internal
    - apache_beam.internal.gcp
    - apache_beam.io
    - apache_beam.io.flink
    - apache_beam.io.gcp
    - apache_beam.io.gcp.datastore
    - apache_beam.io.gcp.internal
    - apache_beam.io.gcp.tests
    - apache_beam.metrics
    - apache_beam.options
    - apache_beam.portability
    - apache_beam.portability.api
    - apache_beam.runners
    - apache_beam.runners.dataflow
    - apache_beam.runners.direct
    - apache_beam.runners.interactive
    - apache_beam.runners.interactive.display
    - apache_beam.runners.job
    - apache_beam.runners.portability
    - apache_beam.runners.test
    - apache_beam.runners.worker
    - apache_beam.testing
    - apache_beam.testing.benchmarks
    - apache_beam.testing.benchmarks.nexmark
    - apache_beam.testing.benchmarks.nexmark.models
    - apache_beam.testing.benchmarks.nexmark.queries
    - apache_beam.tools
    - apache_beam.transforms
    - apache_beam.typehints
    - apache_beam.utils


about:
  home: https://beam.apache.org
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Apache Beam: An advanced unified programming model'

  description: |
    Apache Beam is an open source, unified model for defining both batch
    and streaming data-parallel processing pipelines. Using one of the open
    source Beam SDKs, you build a program that defines the pipeline. The
    pipeline is then executed by one of Beam’s supported distributed
    processing back-ends, which include Apache Apex, Apache Flink, Apache
    Spark, and Google Cloud Dataflow.
  doc_url: https://beam.apache.org/documentation/
  dev_url: https://github.com/apache/beam

extra:
  recipe-maintainers:
    - sodre
    - aaltay
