{% set name = "apache-beam" %}
{% set version = "2.30.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 89e3bace7385560646cc5d1e858182a40054e16ebd01c563638ef12db8ecc012

build:
  number: 0
  # py39 versions of python-avro and dill are too recent
  skip: true  # [win or py<36 or py>=39]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - cython >=0.28.1
    - pip
  run:
    - python
    - cython >=0.28.1
    - python-avro >=1.8.1,!=1.9.2,<1.10.0
    - crcmod >=1.7,<2.0
    - dataclasses  # [py<37]
    - dill >=0.3.1.1,<0.3.2
    - fastavro >=0.21.4,<2
    - future >=0.18.2,<1.0.0
    - grpcio >=1.29.0,<2
    - python-hdfs >=2.1.0,<3.0.0
    - httplib2 >=0.8,<0.20.0
    - numpy >=1.14.3,<1.21.0
    - oauth2client >=2.0.1,<5
    - protobuf >=3.12.2,<4
    - pyarrow >=0.15.1,<4.0.0
    - pydot >=1.2.0,<2
    - python-dateutil >=2.8.0,<3
    - pymongo >=3.8.0,<4.0.0
    - pytz >=2018.3
    - requests >=2.24.0,<3.0.0
    - typing-extensions >=3.7.0,<3.8.0


test:
  requires:
    - pip
  imports:
    - apache_beam
    - apache_beam.coders
    - apache_beam.examples.complete.game
    - apache_beam.examples.complete.juliaset
    - apache_beam.examples.complete.juliaset.juliaset
    - apache_beam.examples.cookbook
    - apache_beam.examples.flink
    - apache_beam.examples.snippets
    - apache_beam.internal
    - apache_beam.internal.gcp
    - apache_beam.io
    - apache_beam.io.flink
    - apache_beam.io.gcp
    - apache_beam.io.gcp.datastore
    - apache_beam.io.gcp.internal
    - apache_beam.io.gcp.tests
    - apache_beam.metrics
    - apache_beam.options
    - apache_beam.portability
    - apache_beam.portability.api
    - apache_beam.runners
    - apache_beam.runners.dataflow
    - apache_beam.runners.direct
    - apache_beam.runners.interactive
    - apache_beam.runners.interactive.display
    - apache_beam.runners.job
    - apache_beam.runners.portability
    - apache_beam.runners.test
    - apache_beam.runners.worker
    - apache_beam.testing
    - apache_beam.testing.benchmarks
    - apache_beam.testing.benchmarks.nexmark
    - apache_beam.testing.benchmarks.nexmark.models
    - apache_beam.testing.benchmarks.nexmark.queries
    - apache_beam.tools
    - apache_beam.transforms
    - apache_beam.typehints
    - apache_beam.utils
  commands:
    - pip check


about:
  home: https://beam.apache.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Apache Beam: An advanced unified programming model'

  description: |
    Apache Beam is an open source, unified model for defining both batch
    and streaming data-parallel processing pipelines. Using one of the open
    source Beam SDKs, you build a program that defines the pipeline. The
    pipeline is then executed by one of Beam’s supported distributed
    processing back-ends, which include Apache Apex, Apache Flink, Apache
    Spark, and Google Cloud Dataflow.
  doc_url: https://beam.apache.org/documentation/
  dev_url: https://github.com/apache/beam

extra:
  recipe-maintainers:
    - sodre
    - aaltay
    - xylar
