travis:
  secure:
    BINSTAR_TOKEN: CdH1tm73kXr3o8GlUXkc4oCb9PccTjxTsCiQUPvCk96Crs42dug8KXN2rwQ6xn1Huz2DJkz6jTqFp841JbdLonF4970CLqLHqctYL14PUPF6HJtWdDhlEPveisSJWX9XCXIWrNKaI01zsPzJetaCKTnKBzMnX3bgYzlcmwHV5saiDJcc+RcSnEqoh2yhGRG6B6V6KBC9ZUtt4GXFmxmRxMmimmsDNgSHrCENH7+Ry2iZR8Sn1ogdFiaIOXBx67JNpzH+IPH1GGGN5GK9CELJm5KHZfzC7AQSVor9pd9j+av8PfwDp4SpVjd/9zkhuGdVFjfSevBN+1nrHO/7Ks9M8rUgWWDyXhYW6jXhcduf3R8XNv83IomFeGC0Act2HA03XGz6PgiWEG/s2f6fv3916gvtdn8qTXYm1gRUxOrSzZg35pIx/ni2+bsz6HxmFx2cwLRPI52ycQMPAK/TWFDA4WfKa6xhrI2WxSRMSPPRFgsRfCIR6Y4NiGBJvcOBuf6SZRsUDRtEqsx1kAvwzLRF1P2wco3KSKBWkbUn1VJicevOqKIkXz+KXe4B7KRncHgZXsQG7XKjeJslha7dK3zLzwUvx1bxbaGm0kmcAJt4y0yUVw8UVQSl1m9MfgpDBdft/r/Oey5lD7dKnjC78x+0Ac/CFhg8jxF6DbNgNBgYpI4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
